version: '3'
services:
   # for mysql
   # database:
   #    image: mysql
   #    container_name: project-name
   #    restart: unless-stopped
   #    volumes:
   #       - ./data:/var/lib/mysql
   #    command:
   #       [
   #          '--character-set-server=utf8mb4',
   #          '--collation-server=utf8mb4_unicode_ci',
   #          --default-authentication-plugin=mysql_native_password,
   #       ]
   #    environment:
   #       MYSQL_ROOT_PASSWORD: 'xxxx'
   #       MYSQL_USER: 'username'
   #       MYSQL_PASSWORD: 'xxxx'
   #       MYSQL_DATABASE: 'database_name'

   # default sqlite
   directus:
      image: directus/directus:10.10.4
      container_name: project-name
      restart: unless-stopped
      ports:
         - 8055:8055
      volumes:
         - ./database:/directus/database
         - ./uploads:/directus/uploads
         - ./extensions:/directus/extensions
      env_file:
         - .env
